import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#060606]`}>
        <div className="w-full relative flex flex-col items-center justify-start pt-[2.062rem] px-[1.25rem] pb-[3.681rem] box-border gap-[6.375rem] leading-[normal] tracking-[normal] text-left text-[1rem] text-white font-h2 mq725:gap-[1.563rem] mq1050:gap-[3.188rem]">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
